version: "3.9"
name: "road_vision"

services:
  mqtt:
    image: eclipse-mosquitto
    container_name: mqtt
    volumes:
      - ./mosquitto:/mosquitto
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    ports:
      - 1883:1883
      - 9001:9001
    networks:
      mqtt_network:

  postgres_db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: test_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/structure.sql:/docker-entrypoint-initdb.d/structure.sql
    ports:
      - "5432:5432"
    networks:
      db_network:


  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      hub_redis:

  store:
    container_name: store
    build: ../../lab2
    depends_on:
      - postgres_db
      - front-end
    restart: always
    environment:
      PG_USERNAME: user
      PG_PASSWORD: pass
      PG_DB: test_db
      PG_HOST: postgres_db
      PG_PORT: 5432
      PORT: 8000
    ports:
      - "8000:8000"
    networks:
      hub_store:
      db_network:
      hub:

  edge:
    container_name: edge
    build: ../../lab4
    depends_on:
      - mqtt
      - front-end
    environment:
      MQTT_BROKER_HOST: "mqtt"
      MQTT_BROKER_PORT: 1883
      MQTT_TOPIC: "agent_data_topic"
      HUB_MQTT_TOPIC: "processed_data_topic"
    networks:
      mqtt_network:
      edge_hub:
      hub:

  hub:
    container_name: hub
    build: ../../lab3
    depends_on:
      - mqtt
      - redis
      - store
      - front-end
    environment:
      REDIS_HOST: "redis"
      REDIS_PORT: 6379
      MQTT_BROKER_HOST: "mqtt"
      MQTT_BROKER_PORT: 1883
      MQTT_TOPIC: "processed_data_topic"
      BATCH_SIZE: 10
      PG_USERNAME: user
      PG_PASSWORD: pass
      PG_HOST: postgres_db
      PG_PORT: 5432
      PG_DB: test_db
    ports:
      - "9000:9000"
    networks:
      mqtt_network:
      hub_store:
      hub_redis:
      db_network:
      

  fake_agent:
    container_name: agent
    build: ../../lab1
    depends_on:
      - front-end
      - mqtt
    environment:
      MQTT_BROKER_HOST: "mqtt"
      MQTT_BROKER_PORT: 1883
      MQTT_TOPIC: "agent_data_topic"
      PARKING_TOPIC: "agent_parking_topic"
      DELAY: 1000
    
    
    networks:
      - mqtt_network

  front-end:
    container_name: front
    build: ../
    environment:
      BASE_URL: "http://store:8000/processed_agent_data"
    ports:
      - "3000:3000"
    networks:
      - hub_store

networks:
  mqtt_network:
  db_network:
  hub_store:
  hub_redis:
  edge_hub:
  hub:

volumes:
  postgres_data:
  pgadmin-data: